os: linux
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y cpanminus libperl-dev make perl
      # For cmake-3.x - probably not needed in trusty.
      # - sudo add-apt-repository ppa:george-edison55/precise-backports -y
    - sudo cpanm File::Temp IO::All Test::Differences Test::More Test::TrailingSpace
perl:
    - "5.24"
python:
    - "3.5"
script: "make test"
